version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gmail-forwarding-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gmail_forwarding
      MYSQL_USER: gmail_user
      MYSQL_PASSWORD: gmail_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gmail-forwarding-app
    environment:
      # Gmail 配置
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      
      # 数据库配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: gmail_user
      DB_PASSWORD: gmail_pass
      DB_NAME: gmail_forwarding
      
      # 应用配置
      APP_PORT: 8080
      CHECK_INTERVAL: 5m
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data: